<a href="https://colab.research.google.com/github/rahul31616/19_Codex_BnB24/blob/main/dsa1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

b = np.empty(2, dtype = int)
print("Matrix b:/n",b)

a = np.empty([2,2], dtype = int)
print("Matrix b:/n",a)

c = np.empty([3,3])
print("nmatrix c:\n",c)


Matrix b:/n [-9093133594791772939      139750158188440]
Matrix b:/n [[       39314536               0]
 [              1 139750139396512]]
nmatrix c:
 [[1.8029107e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [ ]:
import numpy as np

a=np.array([5,72,13,100])
b=np.array([2,5,10,30])

add_ans = a+b
print(add_ans)

add_ans = np.add(a,b)
print(add_ans)

c=np.array([1,2,3,4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a,b,c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


In [3]:
import numpy as np

b = np.zeros(2, dtype=int)
print("matrix b: \n",b)


a = np.zeros([2,2], dtype=int)
print("matrix a: \n",a)

c = np.zeros([3,3])
print("\nmatrix c: \n",c)


matrix b: 
 [0 0]
matrix a: 
 [[0 0]
 [0 0]]

matrix c: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
